language: generic
sudo: false
install:
  - pip install --user -r requirements.txt
  - pyenv install 3.4.6
  - pyenv install 3.6.2
  - pyenv install pypy-5.8.0

script:
  - pyenv global system 2.7 3.4.6 3.5 3.6.2 pypy-5.8.0
  - tox

env:
  - TOXENV=py27
  - OXENV=py34
  - TOXENV=py35
  - OXENV=py36
  - TOXENV=pypy
  - TOXENV=memorytest27
  - TOXENV=memorytest36
  - TOXENV=doctest27
  - TOXENV=coverage-py36
