language: generic
sudo: false
install:
  - pip install --user -r requirements.txt
  - pyenv install 3.5 
  - pyenv install 3.6
  - pyenv install pypy

script:
  - tox

env:
  - TOXENV=py27
  - OXENV=py34
  - TOXENV=py35
  - OXENV=py36
  - TOXENV=pypy
  - TOXENV=memorytest27
  - TOXENV=memorytest36
  - TOXENV=doctest27
  - TOXENV=coverage-py36
