language: python
sudo: false
install:
  - pip install --user -r requirements.txt

script:
  - tox

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: 'pypy'
    env: TOXENV=pypy
  - python: '2.7'
    env: TOXENV=memorytest27
  - python: '3.6'
    env: TOXENV=memorytest36
  - python: '2.7'
    env: TOXENV=doctest27
  - python: '3.6'
    env: TOXENV=coverage-py36
