language: minimal
sudo: false
install:
  - pip install --user -r requirements.txt

#python:
#  - 3.6

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  - TOXENV=memorytest27
  - TOXENV=memorytest36
  - TOXENV=doctest27
  - TOXENV=coverage-py36
